version: '3.8'
services: 
  ihatemoney:
    image: ghcr.io/kikkirej-server/ihatemoney-fork:master
    restart: unless-stopped
    labels: 
      - server.user=${TRAEFIK_IDENT}
      - traefik.enable=true
      - "traefik.http.routers.ihatemoney.rule=Host(`ihatemoney.${DOMAIN}`) || Host(`ihm.${DOMAIN}`)"
      - traefik.http.routers.ihatemoney.entrypoints=websecure
    volumes: 
      - database:/database
    environment: 
      - "ACTIVATE_ADMIN_DASHBOARD=True"
      - "ADMIN_PASSWORD=pbkdf2:sha256:260000$$vTzdALKAttA1wvcw$$acfa12d0778902518341239886e1983de6d5a647c8555799e5a88a44cb3bddd4" #fabcelhaft
      - "SECRET_KEY=gfdtsj;lsdfjg;pdsfjp"
      - "ALLOW_PUBLIC_PROJECT_CREATION=False"
      - "ACTIVATE_DEMO_PROJECT=True"
    networks: 
      - reverse-proxy

volumes: 
  database: {}

networks:
  reverse-proxy:
    external: true
    name: ${LOADBALANCER_NAME}
